include:
  - ./service-config/novnc-audio/compose.yaml
services:
  # obs:
  #   image: obs-headless:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: production
  #   entrypoint: tail -f /dev/null
  #   volumes:
  #     - ./service-config/obs-studio/config:/root/.config/obs-studio
  #   environment:
  #     - DISPLAY=novnc:0.0
  #   ports:
  #     - 4455:4455
  #   depends_on:
  #     novnc:
  #       condition: service_healthy
  obs-builder:
    image: obs-headless:latest
    hostname: obs
    build:
      context: .
      # dockerfile: Dockerfile
      dockerfile: Dockerfile-multistage
      # target: dependencies
      # target: builder
    # entrypoint: tail -f /dev/null
    entrypoint: ./entrypoint.sh
    # volumes:
    #   - ./service-config/obs-studio/config:/root/.config/obs-studio
    #   - ./service-config/obs-studio/entrypoint.sh:/home/obs-studio/entrypoint.sh
    #   - ./service-config/obs-studio/scripts:/home/obs-studio/scripts
    #   - ./service-config/obs-studio/services:/home/obs-studio/services
    #   - ./service-config/obs-studio/logs:/home/obs-studio/logs
    #   - ./service-config/obs-studio/scripts:/opt/scripts
    environment:
      - DISPLAY=novnc:0.0
    ports:
      - 5699:5678 # debugpy port for python script debugging
      - 4455:4455 # websocket port
      - 2000:2000/tcp #SRT just as fallback
      - 2000:2000/udp #SRT input port
    # deploy:
    # resources: # https://docs.docker.com/reference/compose-file/deploy/#resources
    #   limits:
    #     cpus: '0.50'
    #     memory: 50M
    #     pids: 1
    #   reservations:
    #     cpus: '0.25'
    #     memory: 20M
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -v grep | grep 'obs' > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      novnc:
        condition: service_healthy
      proxy:
        condition: service_healthy      
  novnc:  
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
      - RUN_XTERM=no
      # - RUN_FLUXBOX=no
    ports:
      - "8080:8080"
    healthcheck:
        test: "wget -q --spider http://localhost:8080 || exit 1"
        interval: 6s
        timeout: 1s
        retries: 5
  ffmpeg:
    image: jrottenberg/ffmpeg:7.1.1-ubuntu2404-edge
    entrypoint: tail -f /dev/null
    ports: 
      - 1936-1999:1936-1999
      - 2001-2100:2001-2100
  rtmp:
    image: jrottenberg/ffmpeg:7.1.1-ubuntu2404-edge
    # entrypoint: tail -f /dev/null
    entrypoint: bash -c /opt/rtmp/rtmp-server.sh
    volumes:
       - ./service-config/rtmp/output:/opt/rtmp/output
       - ./service-config/rtmp/rtmp-server.sh:/opt/rtmp/rtmp-server.sh
    ports: 
      - 1935:1935
    depends_on:
      obs-builder:
        condition: service_healthy
  player:
    image: nginx:1.28.0-perl
    volumes:
      - ./service-config/frontend/index.html:/usr/share/nginx/html/static/index.html
      - ./service-config/rtmp/output:/usr/share/nginx/html/output
    ports:
      - 8088:80
  # dive:
  #   image: wagoodman/dive:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - 9900:9900
  #   environment:
  #     - DIVE_SOURCE=/var/run/docker.sock
  #   entrypoint: tail -f /dev/null
    # entrypoint: dive server --port 9900